In [1]:
import numpy as np

In [51]:
#Q1- which object doestn't support indexing :- set 

In [52]:
#Q2- to join "data" and "science" with a (-) between them :- "-".join(["data","science"]) & "data"+"-"+"science"

In [30]:
#Q3
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.dot(a,b)
print(c)

[[19 22]
 [43 50]]


In [31]:
#Q4
a=np.arange(10)
b=a[1:5]
b[0]=10
print(a)

[ 0 10  2  3  4  5  6  7  8  9]


In [32]:
#Q5
s={1,2,4,5}
l=[]

for i in range(len(s)):
    l+=[1+i]
print(l)

[1, 2, 3, 4]


In [33]:
#Q6
A={1,'two',3.0,3,27.5,'four',5}
B={27.5,10}
print(A | B)

{1, 3.0, 5, 'four', 10, 27.5, 'two'}


In [34]:
#Q7
t1=(1,2,"tuple",4)
t2=(5,6,7)

In [35]:
x=t2[t1[1]]
print(x)

7


In [36]:
t3=t1+t2
print(t3)

(1, 2, 'tuple', 4, 5, 6, 7)


In [37]:
t3=(t1,t2)
print(t3)

((1, 2, 'tuple', 4), (5, 6, 7))


In [38]:
t3=(list(t1),list(t2))
print(t3)

([1, 2, 'tuple', 4], [5, 6, 7])


In [49]:
#Q8
d={1:"python",2:[1,2,3]}
d[2].append(4)
print(d)

{1: 'python', 2: [1, 2, 3, 4]}


In [40]:
d["one"]=1

In [41]:
d.update({'one':2})

In [42]:
print(d)

{1: 'python', 2: [1, 2, 3, 4], 'one': 2}


In [ ]:
#Q9 which data type is immutable:- tuple

In [43]:
#Q10
student={'name':'jane','age':25,'courses':['Math','statistics']}
student.update({'age':26,'phone':'123-456'})
print(student)

{'name': 'jane', 'age': 26, 'courses': ['Math', 'statistics'], 'phone': '123-456'}


In [44]:
student['phone']='123-456'
student.update({'age':26})
print(student)

{'name': 'jane', 'age': 26, 'courses': ['Math', 'statistics'], 'phone': '123-456'}


In [45]:
#Q11
name="Mahesh"
l=[]
for i in name:
    l.append(i.capitalize())
print(l)

['M', 'A', 'H', 'E', 'S', 'H']


In [47]:
#Q12
a=np.array([range(i,i+4) for i in [1,3,5]])
print(a)

[[1 2 3 4]
 [3 4 5 6]
 [5 6 7 8]]
